spring:
  profiles:
    active: dev #默认为开发环境
  application:
    name: @project.artifactId@
  messages:
    encoding: UTF-8
    basename: i18n/*
    cache-duration: 1
    default-language: zh-CN
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 10MB #设置单个文件最大长度
  main:
    # spring启动后发现的bean会覆盖之前相同名称的bean
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ning.web.entity
  global-config:
    #驼峰下划线转换
    column-underline: true
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true